### ISSUE TITLE
Stellar Pro-213R-N

### ISSUE THREAD

**Issue by belkone** [Reletiv/OpenEPaperLink_TLSR#4]
Hi! :) 

Thank you for your work!

I have a Hanshow's Stellar Pro-213R-N as in the picture:
![IMG_7157](https://github.com/user-attachments/assets/25864434-b70f-4796-8b52-db1da7f5ad0e)

I flashed it using your firmwares from Stellar_2.13_BWR_PRO and Stellar_2.13_BWR directories.
The device refreshes the image and remains in this state: black background and white text (sometimes it refreshes the screen automatically every now and then and returns to the same view):
![IMG_7158](https://github.com/user-attachments/assets/615c0a08-a59a-4d88-bc99-52b761e1d72d)

I can't see it through BLE Scanner (I can see it when I use the firmware from https://github.com/atc1441/ATC_TLSR_Paper/tree/main/Firmware but then nothing happens to the screen).

Could you help me?
If there is any way I can try to debug the problem or provide more information - please let me know! :)

**Comment by Reletiv** [comment]
It's doing exactly what it should! This firmware is for OpenEpaperLink, not for BLE based.. oops

**Comment by belkone** [comment]
Thank you for the reply!
Oh my mistake, I was convinced that tags under OpenEPaperLink also provide BLE.. after the weekend my esps should arrive and then I will run OpenEPaperLink and test it:)

**Comment by Reletiv** [comment]
😂 oops

**Comment by belkone** [comment]
so, my Stellars work great with OpenEPaperLink, thanks!❤️ 

I have 2 more questions: 
1. why are the colors reversed by default? of course I can change it in AP but it causes inconsistency with the preview 😢
3. why is this firmware not in the official repository?!💪🏻

**Comment by Reletiv** [comment]
1, can be inverted in the source code somewhere 
2, because this is very early release,.... for testing only. some don't even contain the latest power saving patches

**Comment by belkone** [comment]
Ok, everything is clear👌🏻
I'm rooting for you!💪🏻
